name: skipatomenv

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pymatgen
  - numpy
  - tqdm
  - pip
  - pip:
      - jax==0.2.5
      - jaxlib==0.1.56
      - tensorflow==2.3.1
      - matminer
