name: skipatomenv

channels:
  - conda-forge

dependencies:
  - python=3.6
  - pymatgen>=2022.0.0
  - numpy=1.18.5
  - tqdm=4.61.1
  - pip
  - pip:
      - jax==0.2.5
      - jaxlib==0.1.56
      - tensorflow==2.3.1
